#ABNF 1.0 gb2312;
language zh-CN; 
mode voice;

root $main;
$main = $where ;
$where = 你好 | 再见 | 谢谢 | 好吃 | 美女 | 张钦源是傻逼  | 妈| 麻|
马|骂|
八|拔|把|爸|
逼|鼻|比|闭|
兄弟|姐妹|爸爸|妈妈|爷爷|奶奶|儿子|女儿|孙子|后妈|


一|二|三|四|五|六|七|九


|没|不好|好的

|西直门

|东直门
|朝阳门
|天安门
 |家庭称呼
 | 数字


 |身体部位
 |颜色
 |代词

 |动词

 |助词

 |第一次见面

 |吃饭
 |时间
 |颜色
 |代词
 |动词
 |助词
|你好
|早上好
|下午好
|晚安 | 


最近怎么样 |


我很好|

你呢 |


我也很好|我|我

 |
好久不见
 |



再见

 |


我们一共三个人

 |
请把菜单拿来 |


菜单上有炒饼丝吗
 |

我想吃包子 |

这个辣椒太辣了

 |
这个开胃菜很好吃 |


这个五分熟的牛排很难吃 |

女服务员很热情 |

我喜欢喝咖啡 |


我讨厌吃鸡肉| 


今天很热

 |
昨天很冷
|

明天会下雨

 |
今天我要去上海
|

明天我要坐飞机
 |

我三点要开会
 |

我每天五点吃晚饭
 |

请问你几点下班
 |

他昨天去哪了
 |

我今天很开心 |

我吃饭了 |

我要去打球 |

他正在学习 |

我已经做完作业了 |


他没有迟到 |


我不回家 |
 
 
这是我的书不是你的书 |

 
我们一起出去玩 |

 
他是个好人 |
 
 
好的 |

 
兄弟 |



姐妹



 |
爸爸

 |
妈妈


 |
爷爷






 |
奶奶


 |
儿子


 |
女儿



 |
孙子


 |
后妈

|
一

 |

二

 

 |
三


 |
四



 |
五



 |
六


 |
七

 |
八



 |
九



 |
十



 |
头



 |
脖子



 |
手



 |
胸


 |
肚子




 |
腿



 |
脚


 |
眼睛


 |
鼻子




 |
毛




 |
红色
 |
绿色







 |
紫色



 |
黑色


 |
白色



 |
橙色

 |
灰色

 |
蓝色



 |
粉色



 |
棕色
|
我 |


我们 |
 
 
你 |
 
 
你们 |
 
 
他 |

 
她 |
 

他们 |

 
它 |
 

我的 |
 
 
 
喜欢 |

 
讨厌 |

 
爱 |

 
打 |


吃 |
 
 
喝 |


学习 |


玩 |


杀 |

 

了 |
 

要 |


正在 |
 
 
已经 |
 
 
没有 |

 
不 |


的 |

 
们 |


好 |



 八


 |拔


 |把


 |爸



 |波


 |伯


 |簸


 |簸











 |逼


 |鼻


 |比


 |闭




 |补


 |不





 |啪


 |爬


 


 |怕





 |坡


 |婆


 |叵


 |破




 |披


 |皮


 |痞


 |屁




 |铺


 |仆


 |普


 |瀑




 |妈


 |麻


 |马


 |骂




 |摸


 |魔


 |抹


 |末


 |
么

 |
咪
 |
 
迷
 |
 
米
 |
 
密








|
模
 
 |
母
 
 |
穆

 |
发
 
 |
罚
 
 |
法
 
 |
髮
 

 |
佛
 

 |
夫
 
 |
福
 
 |
斧
 
 |
富

 |
哒
 
 |
答
 
 |
打
 
 |
大
 
 |



德
 |
 

滴
 
 |
笛
 
 |
底
 |
 
弟
 

 |都 |毒 |赌 |度 |


 他 |
 
塔 |
踏 |



特 |


 
梯 |
题 |
体 |
剃 |





 
秃 |
涂 |
土 |
吐 |





拿 |
哪 |
那 |
 

 
呢 |




泥 |
你 |
腻 |

奴 |
努 |
怒 |

 
女 |


了 |


乐 |
 




 
哩 |
离 |
里 |
力 |

撸 |
炉 |
掳 |
路 |

驴 |
铝 |
绿 |





 
伽 |

嘎 |
尬 |


哥 |
隔 |
镉 |
个 |

估 |
 
古 |
固 |

咖 |

卡 |

科 |
咳 |
渴 |
客 |

哭 |

苦 |
酷 |

哈 |
蛤 |

呵 |
河 |

赫 |

呼 |
湖 |

护 |

鸡 |
急 |
挤 |
记 |

狙 |
菊 |

句 |


家 |
夹 |
假 |
嫁 |

七 |
奇 |
起 |
气 |

蛆 |
渠 |
娶 |
去 |

掐 |

卡 |
髂 |

西 |
习 |
喜 |
细 |

需 |
许 |
栩 |
序 |

虾 |
侠 |

下 |

渣 |
闸 |

炸 |

着 |
哲 |
褶 |
浙 |


猪 |
竹 |
主 |
住 |



插 |
查 |

差 |


车 |

扯 |
撤 |


吃 |
迟 |
尺 |
赤 |


出 |
除 |
楚 |
畜 |



杀 |
啥 |
傻 |
刹 |



奢 |
蛇 |
舍 |
射 |



师 |
石 |
史 |
是 |



叔 |
熟 |
数 |
树 |


惹 |
热 |



日 |


汝 |
乳 |
入 |



砸 |
咋 |



 
啧 |
责 |


资 |

紫 |
字 |

租 |
族 |
组 |


擦 |


测 |

呲 |
慈 |
此 |
刺 |
粗 |
醋 |

仨 |
撒 |
飒 |
色 |
斯 |
死 |
寺 |
苏 |
俗 |
速 |
压 |
牙 |
雅 |
亚 |
椰 |
爷 |
也 |
叶 |

一 |
姨 |
以 |
意 |

淤 |
鱼 |
雨 |
遇 |


蛙 |
娃 |
瓦 |
哇 |
窝 |

我 |
卧 |

污 |
无 |
捂 |
误







 
;